<?php

return [
    'projectdiv' => 'Proyecto Divina Pastora De Las Almas',
    'projectdiv_txt' => 'El 23 de junio de 1703, estando en oración en el coro bajo de su convento el padre capuchino Isidoro de Sevilla, tuvo por inspiración a la Virgen en el traje y título de Pastora, instituyendo una nueva advocación mariana, la Divina Pastora de las Almas, con la que evangelizar al pueblo. Esta nueva devoción sería expandida por el fraile capuchino, sus colaboradores y sucesores, a través de las misiones, donde era portado el icono de la Virgen vestida de Pastora en un estandarte o la fundación de hermandades, cuyo fin principal era el rezo público del Rosario con el referido icono mariano, entre otras herramientas pastorales.<br><br>A través de las misiones, los capuchinos consiguieron sembrar la devoción a la Divina Pastora en todos los lugares del mundo, arraigando de una forma muy especial en España, centro y sur de América y sur de Italia. En torno a esta advocación mariana y la evolución de su devoción, que se adapta a las peculiaridades antropológicas de cada lugar, se desarrollará toda una cultura pastoreña, cuyo producto serán un sinfín de obras de arte.<br><br>El presente proyecto plantea el estudio histórico, artístico y devocional, de una forma crítica y científica del fenómeno cultural y religioso que nace y se desarrolla en torno a la devoción a la Divina Pastora, poniendo en valor la figura de Fray Isidoro de Sevilla, los continuadores de su obra y el apostolado mariano que realizaron; el Convento de Capuchinos de Sevilla, como cuna de la Devoción Pastoreña o las fundaciones piadosas en torno a la Divina Pastora para el fomento y cuidado de su culto, entre otros muchos temas relacionados con la cultura pastoreña.',
    'div_pastora' => 'La Divina Pastora',
    'fisidoro' => 'Fray Isidoro de Sevilla',
    'convsev' => 'El convento de Sevilla'
];
